# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint workflow files
on:
  pull_request:
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  push:
    branches:
      - develop
      - trunk
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-workflow-lint.yml@33705f771525b0d691ee821c90e0c10b18e02871 # 1.2.1
